# Generated by Django 5.1.6 on 2025-03-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(blank=True, max_length=100, null=True)),
                ('podnaslov', models.IntegerField(blank=True, null=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='album')),
                ('datum_uploada', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
