# Generated by Django 5.1.6 on 2025-03-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slika',
            name='sirina',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='slika',
            name='visina',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='slika',
            name='podnaslov',
            field=models.CharField(blank=True, null=True),
        ),
    ]
