# Generated by Django 5.1.6 on 2025-03-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivas', '0002_slika_sirina_slika_visina_alter_slika_podnaslov'),
    ]

    operations = [
        migrations.AddField(
            model_name='slika',
            name='kategorija',
            field=models.CharField(blank=True, choices=[('corporate', 'Corporate Events'), ('concert', 'Concert and Touring'), ('sport', 'Sporting Events'), ('ambition', 'Exhibitions'), ('broadcast', 'TV Broadcasting')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slika',
            name='podnaslov',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
